---
###############################################################
#                         Users Database                      #
###############################################################

# This file can be used if you do not have an LDAP set up.

# List of users
users:
  john:
    displayname: John Doe
    # plaintext is john
    password: $argon2id$v=19$m=65536,t=3,p=4$a3dPWFVHeDY0UkJYb041Ug$aQZx9+pNGXt8hw9S7CkfIBlb1cJIuPUIs3nhB7oz2vw
    email: john@example.com
    groups:
      - admins
      - dev
...
