name: Docker workflow
on: [push]
concurrency:
  group: build-${{ github.ref }}
  cancel-in-progress: true
jobs:
  docker:
    runs-on: ubuntu-20.04
    if: github.event_name == 'push' && (startsWith(github.event.ref, 'refs/tags/') || startsWith(github.event.ref, 'refs/heads/v') || github.event.ref == 'refs/heads/main')
    steps:
      - uses: actions/checkout@v3.0.0

      - name: Cache Docker layers
        uses: actions/cache@v2.1.7
        with:
          path: /tmp/.buildx-cache
          key: ${{ runner.os }}-buildx-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}-buildx-
      - name: Docker meta
        id: docker_meta
        uses: docker/metadata-action@v3.6.2
        with:
          images: cherry

      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v1
        with:
          version: latest

      - name: Builder instance name
        run: echo ${{ steps.buildx.outputs.name }}
      - name: Available platforms
        run: echo ${{ steps.buildx.outputs.platforms }}

      - name: Login to r.haishan.me
        uses: docker/login-action@v1.14.1
        with:
          registry: r.haishan.me
          username: ${{ secrets.R_HAISHAN_ME_USERNAME }}
          password: ${{ secrets.R_HAISHAN_ME_PASSWORD }}

      # - name: Login to Docker Hub
      #   uses: docker/login-action@v1.14.1
      #   with:
      #     username: ${{ github.actor }}
      #     password: ${{ secrets.DOCKER_HUB_PASSWORD }}

      # - name: Login to GHCR
      #   uses: docker/login-action@v1.14.1
      #   with:
      #     registry: ghcr.io
      #     username: ${{ github.actor }}
      #     password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./Dockerfile
          # platforms: linux/amd64,linux/arm/v7,linux/arm64
          platforms: linux/amd64
          push: true
          tags: r.haishan.me/${{ steps.docker_meta.outputs.tags }}
          # tags: ${{ steps.docker_meta.outputs.tags }},ghcr.io/${{ steps.docker_meta.outputs.tags }}
          labels: ${{ steps.docker_meta.outputs.labels }}
          cache-from: type=gha
          cache-to: type=gha

      - name: Image digest
        run: echo ${{ steps.docker_build.outputs.digest }}

      - name: Send Notification
        uses: haishanh/actions-telegram-notification@v1
        if: ${{ always() }}
        with:
          notification-token: ${{ secrets.TG_NOTIFICATION_TOKEN }}
          job-status: ${{ job.status }}
